### ISSUE TITLE
Why is every file is a folder?

### ISSUE THREAD

**Issue by josve05a** [WPCleaner/wpcleaner#10]
Why is everything of this project in a folder (WPCleaner/wpcleaner/WikipediaCleaner)? Why not move all that content out to the head (WPCleaner/wpcleaner)? That way, GitHub will not complain (https://github.com/WPCleaner/wpcleaner/community) that there is no license for this project (since currently it is hidden in the folder instead of in the head). Also, it is odd that the readme is in the head, but not the license etc.

**Comment by WPCleaner** [comment]
At the beginning, the idea was to be able to define different sub-projects in the root folder, but I never did it (I'm still considering doing something like that, but that's a lot of work to split the project in various components)

At the beginning also, there was only the README.txt and LICENSE.txt files in the folder. I added README.md at the root later when I migrated the source code to GIT to benefit from github automatically displaying it while browsing the project repository

**Comment by WPCleaner** [comment]
Moved to Phabricator https://phabricator.wikimedia.org/T256232
