### ISSUE TITLE
How to build the jar without entering a password?

### ISSUE THREAD

**Issue by bfontaine** [WPCleaner/wpcleaner#12]
Hello there,
I tried building WPCleaner running `ant`, but it asks for a password:
```
main:
    [input] Please enter Password for keystore:
```

The build fails with no password, and it also fails with a dummy one:
```
  [signjar] jarsigner error: java.lang.RuntimeException: keystore load: Keystore was tampered with, or password was incorrect
```

How can I bypass it? I’m trying to install WPCleaner without using getdown; I don’t want automatic updates.

**Comment by WPCleaner** [comment]
Hello.

I modified build.xml so that jar files are not signed if WPCleaner.p12 is missing (by default, I do not provide any WPCleaner.p12 file).
Can you get the last version of the source files and try again ?

**Comment by WPCleaner** [comment]
By the way, you can also do a first installation with getdown so that everything needed gets downloaded, and after that run WPCleaner directly without using getdown.
If this kind of solution suits you, I can look into one of my setup what is the exact command to run, but it's something like the following (just need to include every jar in libs in the classpath) :
`java -cp "WPCleaner.jar;libs/*" org.wikipediacleaner.WikipediaCleaner`

**Comment by bfontaine** [comment]
Thanks! Unfortunately it stills asks me for a password :/

I got it to work by [downloading the files listed here](https://tools.wmflabs.org/wpcleaner/wpcleaner/digest.txt) and running the jar with the command you posted above: https://github.com/bfontaine/homebrew-utils/blob/cd68f35db0201a0441d08f3e5b40fe5b12a45a3a/Formula/wpcleaner.rb#L62-L65

I still need to figure out why it doesn’t find the `LICENSE`/`NOTICE` files but otherwise it seems to work. Thank you for your help!

**Comment by bfontaine** [comment]
After some back-and-forth I found how to make it work: you have to add the _directory_ in the classpath, not the individual files. So if the license files are installed under `libs`, running `java -cp "WPCleaner.jar;libs/*:libs" org.wikipediacleaner.WikipediaCleaner` works.

By the way, thank you for your work here; WPCleaner super useful!
