### ISSUE TITLE
action=login is deprecated

### ISSUE THREAD

**Issue by Arenlor** [WPCleaner/wpcleaner#14]
Just putting it here so it can be tracked:

[Thread-0] WARN  o.w.api.request.BasicApiResult - Warning reported: main - Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce> for notice of API deprecations and breaking changes. Use [[Special:ApiFeatureUsage]] to see usage of deprecated features by your application.

[Thread-0] WARN  o.w.api.request.BasicApiResult - Warning reported: login - Main-account login via "action=login" is deprecated and may stop working without warning. To continue login with "action=login", see [[Special:BotPasswords]]. To safely continue using main-account login, see "action=clientlogin".

**Comment by WPCleaner** [comment]
Moved to Phabricator https://phabricator.wikimedia.org/T256231
