### ISSUE TITLE
WPCleaner is apparently not COSMETICBOT compliant with respect to English Wikipedia.

### ISSUE THREAD

**Issue by afarlie** [WPCleaner/wpcleaner#9]
Persuant to concerns raised here :
https://en.wikipedia.org/wiki/Wikipedia:Administrators%27_noticeboard/Incidents#Unauthorized_bot_job.2C_unresponsive_operator

and

https://en.wikipedia.org/wiki/Wikipedia_talk:WPCleaner#COSMETICBOT_compliance

Also In the list of errors presented in the 'semi-automated' portion in relation to CheckWiki,  the top drop box allowing selection of the check wiki error type, should be modified to indicate which are considered "cosmetic" (per the list held on the relevant Project Page at Wikipedia).
(as WPCleaner has to load the list of errors from somewhere, it could also reasonably load information as to which are merely "cosmetic".)

If it's not possible to do this, then consider putting a prominent general warning elsewhere in the program (like the Bot Warning in the documentation.), even though editors are expected to exercise common sense.

**Comment by WPCleaner** [comment]
I'm going to reject this, as explained in https://en.wikipedia.org/wiki/Wikipedia_talk:WPCleaner#COSMETICBOT_compliance

There's already a prominent warning in the bot tools window, designed to alert users that they may require a bot status to use features there
